pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: A
  jobs:
  - job: A1
  - job: A2

- stage: B
  jobs:
  - job: B1
  - job: B2
jobs:
- job: Firstjob
  timeoutInMinutes: 10
  steps:
  - bash: echo "The First job"

- job: Secondjob
  steps:
  - bash: echo "Our Second Pipeline"

- job: Thirdjob
  timeoutInMinutes: 10
  steps:
    - bash: echo "the third job"